#include<iostream>
#include<stdio.h>
#include<cstring>
using namespace std;
int main()
{	 
	short a;
	int b;
	long long c;
	long d;
	unsigned g;
	int long long unsigned h;
	unsigned short i;
	unsigned long j;
	float k;
	double l;
	char m;
	printf("short ");
	scanf("%hi",&a);
	printf("%i\n",a);
	printf("%u\n",a);
	printf("%o\n",a);
	printf("%X",a);
	printf("\nint ");
	scanf("%i",&b);
	printf("\n%lli\n",b);
	printf("%u\n",b);
	printf("%o\n",b);
	printf("%x",b);
	printf("\nlong long ");
	scanf("%lli",&c);
	printf("%lli\n",c);
	printf("%u",c);
	printf("\n%o",c);
	printf("\n%X\n",c);
	printf("long ");
	scanf("%li",&d);
	printf("%li\n",d);
	printf("%u",d);
	printf("\n%o\n",d);
	printf("%X",d);
	printf("\nunsigned short ");
	scanf("%hu",&i);
	printf("%d\n",i);
	printf("%hu",i);
	printf("\n%o\n",i);
	printf("%X",i);
	printf("\nunsigned int ");
	scanf("%iu",&g);
	printf("%d\n",g);
	printf("%u",g);
	printf("\n%o\n",g);
	printf("%X\n",d);
	printf("unsigned long ");
	scanf("%lu",&j);
	printf("%d\n",j);
	printf("%lu",j);
	printf("\n%o\n",j);
	printf("%X",j);
	printf("\nunsigned long long ");
	scanf("%llu",&h);
	printf("%d\n",h);
	printf("%llu",h);
	printf("\n%o\n",h);
	printf("%X",h);
	printf("\nfloat ");
	scanf("%f",&k);
	printf("%f\n",k);
	printf("%e",k);
	unsigned *fp;
	fp=(unsigned *)&k;
	printf("%08o\n",*fp);
	printf("%08X\n",*fp);
	printf("double ");
	scanf("%lf",&l);
	printf("%lf\n",l);
	printf("%le",l);
	unsigned long long *dp;
	dp=(unsigned long long *)&l;
	printf("%016llo\n",*dp);
	printf("%016llX\n",*dp);
	printf("char ");
	scanf(" %c",&m);
	printf("%c\n",m);
	printf("%d\n",m);
	printf("%o\n",m);
	printf("%X",m);
}

